
title: TheCase
url: "https://blog.repulsor.net" 
baseurl: ""

tagline: infrequent notes on random experiments

description: ""

lang: en-us

logo: /assets/img/profile.jpg

author:
  name:       TheCase
  email:      blog@repulsor.net
  about:      geek dad + cenosillicaphobic technology automator
  picture:    
    path:     /assets/img/profile.jpg
    srcset:
      1x:     /assets/img/profile.jpg
      2x:     /assets/img/profile.jpg

  social:
    github:   TheCase
    twitter:  TheCaseB
    linkedin: "bryan-casey-7920541"
    rss:      /feed.xml

# Build settings
markdown: kramdown
#remote_theme: "qwtel/hydejack"
remote_theme: "qwtel/hydejack@v9.1.6"

hydejack:
  post_addons:         [about, related, random, comments]
  project_addons:      [about, other, comments]

  no_mark_external:    false
  no_push_state:       false
  no_drawer:           true
  no_navbar:           true
  no_search:           true
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false

  use_lsi:             true
  hide_dates:          false
  hide_last_modified:  true

  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

# for blog layout
paginate:      10
paginate_path: '/:num/'

plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

permalink: /:title/

menu:
- title: Categories
  url:   /categories/
- title: About
  url:   /about/

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

disqus: https-blog-repulsor-net

favicon: /favicon.ico

defaults:
  - scope:
      type: posts
    values:
      comments: true

google_analytics: G-JKH2QH5Y7W 


exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .sass-cache
  - vendor
  - build.sh

