# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: repulsor blog
email: blog@repulsor.net
description: >- # this means to ignore newlines until "baseurl:"
  infrequently updated notes on my random experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.repulsor.net" 
twitter_username: TheCaseB
github_username:  TheCase

# Build settings
markdown: kramdown
remote_theme: "qwtel/hydejack"
hydejack:
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]

  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false

  use_lsi:             true
  cookies_banner:      true
  advertise:           true
  hide_dates:          false
  hide_last_modified:  true

  dark_mode:
    always:            true
    dynamic:           false
    icon:              true

  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

plugins:
  - jekyll-feed
  - jekyll-include-cache

permalink: /:title/

collections:
  synthesizers:
    output: true
    permalink: /tag/:collection/:name

disqus:
  shortname: https-blog-repulsor-net
discus_shortname: https-blog-repulsor-net

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
