# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: repulsor blog
email: blog@repulsor.net
description: >- # this means to ignore newlines until "baseurl:"
  infrequently updated notes on my random experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.repulsor.net" 
twitter_username: TheCaseB
github_username:  TheCase

# Build settings
markdown: kramdown

#theme: minima 
remote-theme: "qwtel/hydejack"
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-include-cache

permalink: /:title/

collections:
  synthesizers:
    output: true
    permalink: /tag/:collection/:name

disqus:
  shortname: https-blog-repulsor-net

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
